version: "3.7"
services: 
  backend:
  container_name: back-end
    image: springcommunity/spring-petclinic-rest:latest
    ports:
    - target: 9966
      published: 9966
      protocol: tcp


  frontend:
    container_name: front-end
    build: 
      context: ./front-end/
      dockerfile: Dockerfile
    image: arichards98/frontend:latest
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    depends_on:
    - backend 